### ISSUE TITLE
Where to put the python script?

### ISSUE THREAD

**Issue by PatMyron** [brentonmallen1/cloudformation_multiple_gsi#1]
I liked this blog post and solution. However, I was confused on where to put the python lambda script so that CloudFormation could reference it. With a continuous pipeline feeding into dozens of different AWS accounts, I'd like to avoid manual actions per account. Was this what that packaging link in the last paragraph of the blog was talking about?

**Comment by brentonmallen1** [comment]
Sorry for the delayed response, I didn't see this till now.  I think the answer to your question (if I understand correctly) is that you specify where your python code is here https://github.com/brentonmallen1/cloudformation_multiple_gsi/blob/master/multiple_gsi_cf_template.yml#L23

e.g. you point it to the local path
